version: '3.4'
services:
  easy_ssb_pub:
    build:
      context: .
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - ./docker_volumes/.ssb:/root/.ssb
    container_name: easy-ssb-pub
    restart: unless-stopped
